# For detailed information about docker-compose visit https://docs.docker.com/compose/
# To start all docker containers required to execute the tests locally run:
# docker-compose up

version: '2'
services:
  cassandra:
    image: cassandra:3
    ports:
      - "9042:9042"
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
  mqtt:
    image: toke/mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/src/test/travis:/mqtt/config/conf.d
  dynamodb:
    image: deangiberson/aws-dynamodb-local
    ports:
      - "8001:8000"
  ironauth:
    image: iron/auth
    ports:
      - "8090:8090"
  ironmq:
    image: iron/mq
    links:
      - "ironauth:ironauth"
    environment:
      - "AUTH_HOST=http://ironauth:8090"
    ports:
      - "8080:8080"

