# For detailed information about docker-compose visit https://docs.docker.com/compose/
# To start all docker containers required to execute the tests locally run:
# docker-compose up

version: '2'
services:
  cassandra:
    image: cassandra:3
    ports:
      - "9042:9042"
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
  mqtt:
    image: toke/mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/src/test/travis:/mqtt/config/conf.d
  dynamodb:
    image: deangiberson/aws-dynamodb-local
    ports:
      - "8001:8000"
  geode:
    container_name: geode
    image: apachegeode/geode
    hostname: geode
    mem_limit: 2g
    expose:
      - "10334"
      - "1099"
      - "7575"
      - "40404"
    ports:
      - "1099:1099"
      - "10334:10334"
      - "7575:7575"
      - "7070:7070"
      - "40404:40404"
      - "8081:8080"
    volumes:
      - ./geode/scripts/:/scripts/
    command: /scripts/geode.sh
  ironauth:
    image: iron/auth
    ports:
      - "8090:8090"
  ironmq:
    image: iron/mq
    links:
      - "ironauth:ironauth"
    environment:
      - "AUTH_HOST=http://ironauth:8090"
    ports:
      - "8080:8080"
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
  hbase:
    image: yiftizur/hbase-docker:ver-1.2.4
    hostname: hbase
    ports:
      - 60000:60000
      - 60010:60010
      - 60020:60020
      - 60030:60030
    links:
      - zookeeper:zookeeper

