name: Basic Checks

on:
  pull_request:
  push:
    branches:
      - master
      - main
    tags-ignore:
      - v*

jobs:
  style-compile-mima:
    name: Compile, Code Style, Binary Compatibility
    runs-on: ubuntu-20.04
    env:
      JAVA_OPTS: -Xms2G -Xmx2G -Xss2M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: # https://github.com/olafurpg/setup-scala#faster-checkout-of-big-repos
          fetch-depth: 100

      - name: Fetch tags
        run: git fetch --depth=100 origin +refs/tags/*:refs/tags/*

      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.3

      - name: "Code style, compile tests, MiMa. Run locally with: sbt ++2.13.8 verifyCodeStyle; Test/compile; mimaReportBinaryIssues"
        run: sbt "++2.13.8 verifyCodeStyle; Test/compile; mimaReportBinaryIssues"

  documentation:
    name: ScalaDoc, Documentation with Paradox
    runs-on: ubuntu-20.04
    env:
      JAVA_OPTS: -Xms2G -Xmx2G -Xss2M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: # https://github.com/olafurpg/setup-scala#faster-checkout-of-big-repos
          fetch-depth: 100

      - name: Fetch tags
        run: git fetch --depth=100 origin +refs/tags/*:refs/tags/*

      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.3

      - name: "Create all API docs and create site with Paradox"
        run: sbt "unidoc; docs/paradox"
