name: License and vulnerabilties scanning

on:
  pull_request:
  push:
    branches:
      - master
      - main
    tags-ignore:
      - v*

jobs:
  license-and-vulnerabilities-scanning:
    name: Analyse
    if: github.repository == 'akka/alpakka'
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: # https://github.com/olafurpg/setup-scala#faster-checkout-of-big-repos
          fetch-depth: 100
      - name: Fetch tags
        run: git fetch --depth=100 origin +refs/tags/*:refs/tags/*
      - name: Install Fossa CLI
        run: |-
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
      - name: Analyse
        env:
          # The FOSSA_API_KEY is configured on Akka organisation level
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        run: fossa analyze
