name: Link Validator

on:
  schedule:
    - cron:  '0 6 * * 1'

jobs:
  validate-links:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: coursier/setup-action@v1
        with:
          jvm: adopt:11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v5

      - name: sbt site
        run: sbt docs/makeSite

      - name: Run Link Validator
        run: cs launch net.runne::site-link-validator:0.2.2 -- scripts/link-validator.conf
