name: Link Validator

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 6 * * 1'

jobs:
  validate-links:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: # https://github.com/olafurpg/setup-scala#faster-checkout-of-big-repos
          fetch-depth: 100

      - name: Fetch tags
        run: git fetch --depth=100 origin +refs/tags/*:refs/tags/*

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.2

      - name: Set up JDK 11
        uses: coursier/setup-action@v1
        with:
          jvm: adopt:11
          apps: cs

      - name: sbt site
        run: sbt docs/makeSite

      - name: Run Link Validator
        run: cs launch net.runne::site-link-validator:0.2.3 -- scripts/link-validator.conf
